apiVersion: v1
kind: Service
metadata:
  name: switchyard-gateway
  labels:
    app.kubernetes.io/name: switchyard-gateway
spec:
  selector:
    app.kubernetes.io/name: switchyard-gateway
  ports:
    - name: http
      port: 8000
      targetPort: http
